# 网站的基本配置
title: 个人介绍   # 网站标题
description: 王泓杰的个人介绍   # 网站描述
author: 王泓杰    # 名字
logo: /static/img/photo.jpg    # 头像
github: https://github.com/mkbk11   # GitHub 主页链接
about: 勤奋，坚持，专研，开朗   # 关于我的简短描述

# w网站 URL 配置
baseurl: "/whj-github.io"   #
url: "https://mkbk11.github.io"   # GitHub Pages域名

# 搜索功能配置
allowsearch: true   # 是否启用站内搜索功能

# 评论系统配置
disqus_shortname: aboutashu
google_analytics: UA-72862926-1

# 社交媒体分享配置
# share:
#   twitter_username: \#
#   fb_appid: 000000000000

# 标签系统配置
enableTags: true
tagarray: []

paginate: 20    # 每页显示的文章数量
per_page: 20    # 每页显示的文章数量（用于某些特定页面）
paginate_path: "/page:num/"   # 分页 URL 的格式
markdown: kramdown    # Markdown 解析器配置
gems: [jekyll-paginate, jekyll-gist]    # Jekyll 插件配置
 